### ISSUE TITLE
[Bug] CustomEconomies

### ISSUE THREAD

**Issue by cobrex1** [Cold-Development/MoneyPouchDeluxe#3]
Hi there,
Following the last update to 1.3.4, all my custom economies have become invalid. They were all working in 1.3.3.  Logs only show that they are invalid.

Did I miss something I needed to change in the yml files with this last update?

Thanks

**Comment by padrewin** [comment]
Hey, @cobrex1!
They were indeed removed by mistake. 
Can you check latest `v1.4.1` version? this includes CustomEconomy.
https://github.com/Cold-Development/MoneyPouchDeluxe/releases/tag/v1.4.1

_Sorry for the delay_ 😢
Please reach me back if your issue persist or its fixed!

**Comment by cobrex1** [comment]
Thanks all fixed on the last update :)
