### ISSUE TITLE
Claim Block Reward Option

### ISSUE THREAD

**Issue by InvisibleSpiders** [Cold-Development/MoneyPouchDeluxe#5]
**Feature**:
Hook into [GriefPrevention](https://github.com/GriefPrevention/GriefPrevention/tree/16.18.4) and [HuskClaims](https://github.com/WiIIiam278/HuskClaims) and allow for claim block rewards.

**Improvement**:
Add a reward type for "claim blocks" and detect either plugin on start to support the reward type. 

I wish I could help with a fork/coding but I have NO idea how to do that. Sorry!

**Comment by InvisibleSpiders** [comment]
HuskClaims is open source and API is available here: https://william278.net/docs/huskclaims/api#developers

**Comment by padrewin** [comment]
> **Improvement**: Add a reward type for "claim blocks" and detect either plugin on start to support the reward type.

Could you detail more about this? 
What should be the reward type "claim blocks" and in what way would GriefPrevention or HuskClaims impact moneypouch?
I see that those 2 plugins are anti-grieffing plugins, and my plugin is about opening some "pouches" to get rewards.

**Comment by InvisibleSpiders** [comment]
Sure thing! 

So in GP and HC, the only way to earn claim blocks (to claim your land with) is to play and accrue blocks just by being active, or to purchase the blocks with money (if the server dev has that enabled). 

The rewards from the pouches could be random quantities of claim blocks that the player can use for his land.

Essentially this can either allow the players to win more blocks from crates or rewards set by the devs, or keep the pouch to sell in player shops/give away as they see fit.

**Comment by padrewin** [comment]
So from what I understand you want the player to be able to earn a pouch for example "Land Pouch" and when he opens it, can get a number of blocks that he can use for his lands
Basically a custom "currency" instead of money, blocks for lands?

**Comment by InvisibleSpiders** [comment]
Yeah, basically! 

Both plugins handle their own claim blocks but your plugin would be a unique and fun way to reward extra blocks for the player to use.

**Comment by padrewin** [comment]
This plugin already have a feature named "Custom Economy Type", isn't that helping you with this?
Check [this](https://github.com/Cold-Development/MoneyPouchDeluxe/tree/master/src/main/resources/customeconomytype)
In the "customeconomytype" folder you can create a yml file named however you want, for example "landsblock.yml" and just copy paste the entire content from the "customeconomytype.yml" and replace the command:

`transaction-prize-command: "give %player% %prize%"` -- replace the command "give" with the command from your desired plugin
so let's say the command from your plugins is: "`huskclaims give %player% %prize%`"

**Comment by InvisibleSpiders** [comment]
Oh yeah, that actually would work perfectly.
My apologies, I didn't see this part of the plugin.

Thanks for sharing :)

**Comment by padrewin** [comment]
Not a problem, glad this is working as expected for your requirements! 🙏🏼 ❤️
